### ISSUE TITLE
Missing Job ID - Jobs waiting in queue

### ISSUE THREAD

**Issue by lfritsche** [bigappleinsider/browserstackapi#2]
Hi @bigappleinsider 

After solving the previous issue migrating the DB (which was due to the missing ENV variable set to production) we have almost reached the point where everything works except from one last thing:

[2018-06-24 14:39:02] production.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException in /home/screenshots/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:210
Stack trace:
#0 /home/screenshots/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php(197): Illuminate\Routing\RouteCollection->methodNotAllowed(Array)
#1 /home/screenshots/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php(145): Illuminate\Routing\RouteCollection->getOtherMethodsRoute(Object(Illuminate\Http\Request), Array)
#2 /home/screenshots/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1054): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#3 /home/screenshots/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1022): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#4 /home/screenshots/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#5 /home/screenshots/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 /home/screenshots/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 /home/screenshots/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#8 /home/screenshots/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#9 /home/screenshots/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#10 /home/screenshots/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#11 /home/screenshots/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#12 /home/screenshots/public/index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []

After submitting a csv I see the database log, but although waiting for some time, no Job ID is set.
The only debug message I could find was the one above (laravel.log). I already debuged beanstalked and supervisord as far as I could and also recognized the process beeing added to the queue, but nothing happens afterwards except the issue above.

Additional Note, we are not using mailchimp / no mailchimp api key has been provided in the env.php
But I don't think this should be the problem above?
curl to the browserstack API from console is also working. mod_rewrite enabled.

I tried it with one url, multiple URLs, http & https & without http/s, but the problem looks like being located elsewhere.

Thank you for your great tool - would be great to use it day by day.

Cheers  -  Leander

**Comment by bigappleinsider** [comment]
ID is set here: 

https://github.com/bigappleinsider/browserstackapi/blob/master/app/controllers/ScreenshotsApi.php

You could try logging to check if supervisor is running
